// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// directed_louvain_fast
IntegerVector directed_louvain_fast(NumericMatrix edges, double precision, double gamma, bool renumbering, bool randomized, int level, bool verbose);
RcppExport SEXP _DirectedLouvainR_directed_louvain_fast(SEXP edgesSEXP, SEXP precisionSEXP, SEXP gammaSEXP, SEXP renumberingSEXP, SEXP randomizedSEXP, SEXP levelSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type renumbering(renumberingSEXP);
    Rcpp::traits::input_parameter< bool >::type randomized(randomizedSEXP);
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(directed_louvain_fast(edges, precision, gamma, renumbering, randomized, level, verbose));
    return rcpp_result_gen;
END_RCPP
}
// directed_modularity_fast
double directed_modularity_fast(NumericMatrix edges, IntegerVector partition);
RcppExport SEXP _DirectedLouvainR_directed_modularity_fast(SEXP edgesSEXP, SEXP partitionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type partition(partitionSEXP);
    rcpp_result_gen = Rcpp::wrap(directed_modularity_fast(edges, partition));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DirectedLouvainR_directed_louvain_fast", (DL_FUNC) &_DirectedLouvainR_directed_louvain_fast, 7},
    {"_DirectedLouvainR_directed_modularity_fast", (DL_FUNC) &_DirectedLouvainR_directed_modularity_fast, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DirectedLouvainR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
