# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

directed_louvain_fast <- function(edges, precision = 0.0001, gamma = 1.0, renumbering = FALSE, randomized = TRUE, level = -2L, verbose = FALSE) {
    .Call(`_DirectedLouvainR_directed_louvain_fast`, edges, precision, gamma, renumbering, randomized, level, verbose)
}

directed_modularity_fast <- function(edges, partition) {
    .Call(`_DirectedLouvainR_directed_modularity_fast`, edges, partition)
}

